services:
  xtls-reality:
    image: ghcr.io/haiboyuwen/xtls-reality:latest
    environment:
      - SNI=www.samsung.com
      - SHORT_ID=aabbccdd
    container_name: xtls-reality
    restart: always
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config:/opt/xray/config
    network_mode: host